int leeftijd = 16;
if (leeftijd <2) {;
  println("Is een baby");
} else if (leeftijd <4) {;
  println("Is een kleuter");
} else if (leeftijd <12) {;
  println("Is een kind");
} else if (leeftijd <20) {;
  println("Is een tiener");
} else if (leeftijd <25) {;
  println("Is een adolescent");
} else if (leeftijd >=25) {;
  println("Is een volwassene");
};
